Backend/config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :soccer_players
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

Backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Backend/app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team_house, class_name: "Team"
  belongs_to :team_outside, class_name: "Team"
end

Backend/app/models/soccer_player.rb
class SoccerPlayer < ApplicationRecord
  belongs_to :team
end

Backend/app/models/team.rb
class Team < ApplicationRecord
  has_many :soccer_players, dependent: :destroy
  has_many :house_matches, class_name: 'Match', foreign_key: :team_house_id, dependent: :destroy
  has_many :outside_matches, class_name: 'Match', foreign_key: :team_outside_id, dependent: :destroy
  
  def match_quatity
    outside_matches = Match.where(team_outside_id: id)
    house_matches   = Match.where(team_house_id: id)

    outside_matches.or(house_matches).count
  end

  def player_quantity
    SoccerPlayer.where(team_id: id).count
  end
end

Backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

Backend/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy!

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:team_house_id, :team_outside_id)
    end
end

Backend/app/controllers/soccer_players_controller.rb
class SoccerPlayersController < ApplicationController
  before_action :set_soccer_player, only: %i[ show edit update destroy ]

  # GET /soccer_players or /soccer_players.json
  def index
    @soccer_players = SoccerPlayer.all
  end

  # GET /soccer_players/1 or /soccer_players/1.json
  def show
  end

  # GET /soccer_players/new
  def new
    @soccer_player = SoccerPlayer.new
    @teams = Team.all
  end

  # GET /soccer_players/1/edit
  def edit
    @teams = Team.all
  end

  # POST /soccer_players or /soccer_players.json
  def create
    @soccer_player = SoccerPlayer.new(soccer_player_params)

    respond_to do |format|
      if @soccer_player.save
        format.html { redirect_to soccer_player_url(@soccer_player), notice: "Soccer player was successfully created." }
        format.json { render :show, status: :created, location: @soccer_player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @soccer_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /soccer_players/1 or /soccer_players/1.json
  def update
    respond_to do |format|
      if @soccer_player.update(soccer_player_params)
        format.html { redirect_to soccer_player_url(@soccer_player), notice: "Soccer player was successfully updated." }
        format.json { render :show, status: :ok, location: @soccer_player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @soccer_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soccer_players/1 or /soccer_players/1.json
  def destroy
    @soccer_player.destroy!

    respond_to do |format|
      format.html { redirect_to soccer_players_url, notice: "Soccer player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soccer_player
      @soccer_player = SoccerPlayer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def soccer_player_params
      params.require(:soccer_player).permit(:name, :number, :team_id)
    end
end

Backend/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy!

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name, :victories, :loses)
    end
end

Backend/app/helpers/application_helper.rb
module ApplicationHelper
end

Backend/app/helpers/matches_helper.rb
module MatchesHelper
end

Backend/app/helpers/soccer_players_helper.rb
module SoccerPlayersHelper
end

Backend/app/helpers/teams_helper.rb
module TeamsHelper
end

Backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Backend/app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :team_house_id, style: "display: block" %>
    <%= form.text_field :team_house_id %>
  </div>

  <div>
    <%= form.label :team_outside_id, style: "display: block" %>
    <%= form.text_field :team_outside_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>Team house:</strong>
    <%= match.team_house_id %>
  </p>

  <p>
    <strong>Team outside:</strong>
    <%= match.team_outside_id %>
  </p>

</div>

Backend/app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

Backend/app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches</h1>

<div id="matches">
  <% @matches.each do |match| %>
    <%= render match %>
    <p>
      <%= link_to "Show this match", match %>
    </p>
  <% end %>
</div>

<%= link_to "New match", new_match_path %>

Backend/app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

Backend/app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>

Backend/app/views/soccer_players/_form.html.erb
<%= form_with(model: soccer_player) do |form| %>
  <% if soccer_player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(soccer_player.errors.count, "error") %> prohibited this soccer_player from being saved:</h2>

      <ul>
        <% soccer_player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :team_id, style: "display: block" %>
    <%= select_tag('soccer_player[team_id]', options_for_select(@teams.pluck(:name, :id))) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/soccer_players/_soccer_player.html.erb
<div id="<%= dom_id soccer_player %>">
  <p>
    <strong>Name:</strong>
    <%= soccer_player.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= soccer_player.number %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= soccer_player.team_id %>
  </p>

</div>

Backend/app/views/soccer_players/edit.html.erb
<h1>Editing soccer player</h1>

<%= render "form", soccer_player: @soccer_player %>

<br>

<div>
  <%= link_to "Show this soccer player", @soccer_player %> |
  <%= link_to "Back to soccer players", soccer_players_path %>
</div>

Backend/app/views/soccer_players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Soccer players</h1>

<div id="soccer_players">
  <% @soccer_players.each do |soccer_player| %>
    <%= render soccer_player %>
    <p>
      <%= link_to "Show this soccer player", soccer_player %>
    </p>
  <% end %>
</div>

<%= link_to "New soccer player", new_soccer_player_path %>

Backend/app/views/soccer_players/new.html.erb
<h1>New soccer player</h1>

<%= render "form", soccer_player: @soccer_player %>

<br>

<div>
  <%= link_to "Back to soccer players", soccer_players_path %>
</div>

Backend/app/views/soccer_players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @soccer_player %>

<div>
  <%= link_to "Edit this soccer player", edit_soccer_player_path(@soccer_player) %> |
  <%= link_to "Back to soccer players", soccer_players_path %>

  <%= button_to "Destroy this soccer player", @soccer_player, method: :delete %>
</div>